tools:
  file-share:
    folder: D:/tmp/fileshare

spring:
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tools?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: postgres
    password: FUWENXING

mybatis:
  configuration:
    map-underscore-to-camel-case: true